### ISSUE TITLE
Plugin doesn't work with SonarQube 7.3

### ISSUE THREAD

**Issue by dzmitry-rudnouski** [jensgerdes/sonar-pmd#49]
Plugin doesn't work with SonarQube 7.3:
`java.lang.IllegalStateException: Fail to load plugin PMD [pmd]
...
Caused by: java.lang.NoClassDefFoundError: org/sonar/api/batch/Sensor`

Caused by https://jira.sonarsource.com/browse/SONAR-10138.

**Comment by dzmitry-rudnouski** [comment]
See also https://github.com/SonarQubeCommunity/sonar-pmd/issues/42

**Comment by jensgerdes** [comment]
Thank you. I'll have a look at it.
